# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181a89d3d559fd85b61b7d9ef55ef2712385d7ba2bf5371af186171b0ea33198300d107f1fdc1968c7e5346feb1c231e669d86d6bcbaadf9f3d1202173deaa2a

test:
  secret_key_base: 62ffa8037c67be4cef5f52e795ae0a078e7ab56f93154be8be7220bf7647356163a4427fe10836b932f3938c1175d40ee90b8f59fb133a8f1592d2e433532b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
